# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:title

# Setup
title:            Alex Bilbie
tagline:          'Developer, Speaker, Whisky Drinker'
description:      'Developer, Speaker, Whisky Drinker'
url:              http://localhost:4000

author:
  name:           'Alex Bilbie'
  url:            https://twitter.com/alexbilbie

paginate:         10
gems:             [jekyll-paginate, jekyll-gist, jekyll-sitemap]